# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/nvme0n1p2_crypt";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."nvme0n1p2_crypt".device = "/dev/disk/by-uuid/0d12f070-7fe1-45ac-bbb9-e1efdca6e54f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/29E7-0445";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/93776f5b-b576-4c43-b189-fff9669dc822"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
